### ISSUE TITLE
지도 첫 위치 변경안 3가지

### ISSUE THREAD

**Issue by chaesunbak** [layout-SY/DaeBang#16]
1. 현재 내 위치로 처음 위치를 설정한다.
2. 서울시 전체가 보이게 위치를 설정한다.
3. 대학생들을 위한어플 답게 여러 대학들(또는 자취하기 좋은 곳들) 위치를 랜덤하게 설정한다.(새로고침하면 매번 바뀌어서 어지울 수 있음)

2번이 가장 좋아보이고 3번도 나쁘지 않은 것 같은데 어떤가요

**Comment by dongguJeong** [comment]
1번이 괜찮은 거 같습니다

**Comment by chaesunbak** [comment]
> 1번이 괜찮은 거 같습니다

오 geolocation api도 써볼수 있고 도전적이고 좋은거 같은데요?

**Comment by layout-SY** [comment]
저도 1번이 좋아 보입니다

**Comment by chaesunbak** [comment]
https://github.com/layout-SY/DaeBang/pull/34

로 반영되었습니다
