### ISSUE TITLE
디테일 리스트 정상적으로 오픈 안 되는 오류

### ISSUE THREAD

**Issue by dongguJeong** [layout-SY/DaeBang#25]
디테일 리스트가 정상적으로 오픈이 안 됨

**Comment by chaesunbak** [comment]
<img width="629" alt="스크린샷 2024-11-25 오후 5 29 00" src="https://github.com/user-attachments/assets/fadc94be-9892-4318-b43f-fa0c46b4d571">
 첫 열때는 안보이면서 이렇게 아래에 뭔가 생기고
 
 두번째부터 잘열립니다

**Comment by chaesunbak** [comment]
rafactor : 시세 데이터 Query로 가져오기 & 오타 수정 #31

이후는 

<img width="280" alt="스크린샷 2024-11-25 오후 8 04 53" src="https://github.com/user-attachments/assets/bda83999-53f2-4b2c-ae65-8ff93c6395e2">

시세리스트 최하단에 표시됩니다

**Comment by chaesunbak** [comment]
(재업) 디테일리스트 열기/닫기 문제 #33
