### ISSUE TITLE
디테일리스트에서 이동 버튼 클릭 했을 때, 지도의 어디로 이동했는지 잘 모르겠습니다

### ISSUE THREAD

**Issue by dongguJeong** [layout-SY/DaeBang#41]
클릭을 하고
<img width="341" alt="스크린샷 2024-11-27 오전 12 47 40" src="https://github.com/user-attachments/assets/3266ddad-6014-4800-8a91-e0e952b58e71">

지도가 움직인 건 알겠는데, 떠 있는 마커들이 많아서 내가 클릭한 건물이 어디있는지 한 번에 파악이 잘 안 됩니다
<img width="659" alt="스크린샷 2024-11-27 오전 12 47 47" src="https://github.com/user-attachments/assets/f3e27822-b8de-49ab-8795-250237fbf67c">

**Comment by layout-SY** [comment]
조금 더 확대하면 될 거 같네요

**Comment by layout-SY** [comment]
그럼 해당 마커 옆에 디테일 버튼이 생기는 건가요?

**Comment by chaesunbak** [comment]
> 그럼 해당 마커 옆에 디테일 버튼이 생기는 건가요?

현재 보고 있는 디테일의 마커는 색깔을 다르게 해보는 방식으로 해보려고 합니다

아니면 조금 더 확대하는 방법도 가능할 것 같아요

**Comment by chaesunbak** [comment]
<img width="1355" alt="스크린샷 2024-11-27 오후 8 38 08" src="https://github.com/user-attachments/assets/4071c464-2c67-4116-9d1c-58ffbb84c43c">


이동하기 버튼 누르면 해당 물건이 지도의 가운데 오게 이동하는데
가운데가 디테일창에 가려져 있어서 잘 안보이게 되네요.

확대하는게 가능할 줄 알았는데 구조적으로 어려운 부분이 있네요

**Comment by chaesunbak** [comment]
해당 요소의 마커를 다르게 표시하는 것도 클러스터링이 되어있는 경우에는 한계가 있는것 같구 ㅠ
